const TipoErro = {
    DATA_INVALIDA: 'DATA_INVALIDA',
    EMAIL_INVALIDO: 'EMAIL_INVALIDO',
    EMAIL_NAO_ENCONTRADO: 'EMAIL_NAO_ENCONTRADO',
    EMAIL_NULO: 'EMAIL_NULO',
    PARCELA_NAO_PODE_MUDAR_MES: 'PARCELA_NAO_PODE_MUDAR_MES',
    USUARIO_NAO_AUTENTICAO: 'USUARIO_NAO_AUTENTICAO',
} as const

export default TipoErro
